stateDiagram-v2
	shop_order_revenue_invalid--> [*]
	style shop_order_revenue_invalid fill:#4CAF50
	team_order_revenue_invalid--> [*]
	style team_order_revenue_invalid fill:#4CAF50
	shop_daily_withdrawal--> shop_order_revenue_invalid
	style shop_daily_withdrawal fill:#4CAF50
	adjustment_log--> shop_order_revenue
	style adjustment_log fill:#4CAF50
	shop_order_revenue--> shop_order_revenue_invalid
	style shop_order_revenue fill:#4CAF50
	adjustment_log--> shop_order_revenue_invalid
	style adjustment_log fill:#4CAF50
	team_daily_withdrawal--> team_order_revenue_invalid
	adjustment_log--> team_order_revenue
	style adjustment_log fill:#4CAF50
	team_order_revenue--> team_order_revenue_invalid
	style team_order_revenue fill:#4CAF50
	adjustment_log--> team_order_revenue_invalid
	style adjustment_log fill:#4CAF50
