stateDiagram-v2
	test.sku_ready_stock--> [*]
	inv_transaction_changes--> sku_ready_stock_temp
	sku_ready_stock_temp--> test.sku_ready_stock
	inv_transaction_changes--> sku_ongoing_stock
	sku_ongoing_stock--> test.sku_ready_stock
