// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
)

// Injectors from wire.go:

func InitializeWorker() (*Worker, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	keyStore := NewKeystore()
	coreConfig := NewStreamCoreConfig()
	processHandler := NewProcessHandler(keyStore)
	periodicSnapshot := NewPeriodicSnapshot(keyStore)
	calculateBalanceHistory := NewCalculateBalanceHistory(db, keyStore)
	calculateFunc := NewCalculate(coreConfig, db, processHandler, periodicSnapshot, calculateBalanceHistory, keyStore)
	statDatabase, err := NewStatDatabase()
	if err != nil {
		return nil, err
	}
	migrator := NewMigrator(statDatabase)
	snapshotFunc := NewSnapshotFunc(keyStore, statDatabase, migrator)
	debugFunc := NewDebugFunc()
	worker := NewWorker(db, keyStore, calculateFunc, snapshotFunc, debugFunc)
	return worker, nil
}
