// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
	"github.com/wargasipil/stream_engine/stream_core"
)

// Injectors from wire.go:

func InitializeWorker() (*Worker, error) {
	coreConfig := NewStreamCoreConfig()
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	hashMapCounter, err := stream_core.NewHashMapCounter(coreConfig)
	if err != nil {
		return nil, err
	}
	processHandler := NewProcessHandler(hashMapCounter)
	periodicSnapshot := NewPeriodicSnapshot(hashMapCounter)
	worker := NewWorker(coreConfig, db, processHandler, periodicSnapshot, hashMapCounter)
	return worker, nil
}
