// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
	"github.com/wargasipil/stream_engine/stream_core"
)

// Injectors from wire.go:

func InitializeWorker() (*Worker, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	coreConfig := NewStreamCoreConfig()
	hashMapCounter, err := stream_core.NewHashMapCounter(coreConfig)
	if err != nil {
		return nil, err
	}
	processHandler := NewProcessHandler(hashMapCounter)
	periodicSnapshot := NewPeriodicSnapshot(hashMapCounter)
	calculateBalanceHistory := NewCalculateBalanceHistory(db, hashMapCounter)
	calculateFunc := NewCalculate(coreConfig, db, processHandler, periodicSnapshot, calculateBalanceHistory, hashMapCounter)
	statDatabase, err := NewStatDatabase()
	if err != nil {
		return nil, err
	}
	migrator := NewMigrator(statDatabase)
	snapshotFunc := NewSnapshotFunc(hashMapCounter, statDatabase, migrator)
	worker := NewWorker(db, hashMapCounter, calculateFunc, snapshotFunc)
	return worker, nil
}
