// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
)

// Injectors from wire.go:

func InitializeWorker() (*Worker, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	configStream := NewConfigStream()
	walStream := NewWalStream()
	runStreamFunc := NewRunStream(db, configStream, walStream)
	worker := NewWorker(runStreamFunc)
	return worker, nil
}
