// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/shared/configs"
)

// Injectors from wire.go:

func InitializeAppReplication() (AppReplication, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	replicationState, err := NewReplicationState()
	if err != nil {
		return nil, err
	}
	getReplication := NewReplication(appConfig, replicationState)
	db, err := NewBadgerDB()
	if err != nil {
		return nil, err
	}
	startFunc := NewStartFunc(getReplication, db)
	backfillFunc := NewBackfillFunc(getReplication, replicationState)
	gormDB, err := NewProductionDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	batchFunc := NewBatch(gormDB)
	appReplication := NewAppReplication(startFunc, backfillFunc, batchFunc)
	return appReplication, nil
}
